import parser
import qa

def pipeline():

    qa_model = qa.QA()   
    qa_model.run()
    # qa_model.run_one_turn("What is the first step?")

if __name__ == "__main__":
    pipeline()


# {'Ingredients': [{'descriptor': 'mini',
#                   'full_text': '6  mini cucumbers',
#                   'measurement': '',
#                   'name': 'mini cucumbers',
#                   'preparation': None,
#                   'quantity': '6'},
#                  {'descriptor': None,
#                   'full_text': '2 teaspoons salt',
#                   'measurement': 'teaspoons',
#                   'name': 'salt',
#                   'preparation': None,
#                   'quantity': '2'},
#                  {'descriptor': 'red',
#                   'full_text': '1/4 cup red onions chopped',
#                   'measurement': 'cup',
#                   'name': 'red onions',
#                   'preparation': None,
#                   'quantity': '1/4'},
#                  {'descriptor': 'seasoned',
#                   'full_text': '1/4 cup rice vinegar seasoned',
#                   'measurement': 'cup',
#                   'name': 'rice vinegar',
#                   'preparation': None,
#                   'quantity': '1/4'},
#                  {'descriptor': 'hot',
#                   'full_text': '3 tablespoons hot honey, such as Mike’s Hot '
#                                'Honey®',
#                   'measurement': 'tablespoons',
#                   'name': 'hot honey',
#                   'preparation': None,
#                   'quantity': '3'},
#                  {'descriptor': None,
#                   'full_text': '2 tablespoons soy sauce',
#                   'measurement': 'tablespoons',
#                   'name': 'soy sauce',
#                   'preparation': None,
#                   'quantity': '2'},
#                  {'descriptor': None,
#                   'full_text': '1 teaspoon sesame oil',
#                   'measurement': 'teaspoon',
#                   'name': 'sesame oil',
#                   'preparation': None,
#                   'quantity': '1'},
#                  {'descriptor': None,
#                   'full_text': '1 teaspoon fish sauce',
#                   'measurement': 'teaspoon',
#                   'name': 'fish sauce',
#                   'preparation': None,
#                   'quantity': '1'},
#                  {'descriptor': 'minced',
#                   'full_text': '2 cloves garlic , minced',
#                   'measurement': 'cloves',
#                   'name': 'garlic',
#                   'preparation': 'minced',
#                   'quantity': '2'},
#                  {'descriptor': 'red to taste',
#                   'full_text': '1/4 teaspoon red pepper flakes , or to taste',
#                   'measurement': 'teaspoon',
#                   'name': 'red pepper flakes',
#                   'preparation': None,
#                   'quantity': '1/4'}],
#  'Methods': ['sprinkle',
#              'combine',
#              'gently',
#              'repeat',
#              'remove',
#              'soften',
#              'spiral',
#              'return',
#              'avoid',
#              'rinse',
#              'whisk',
#              'serve',
#              'place',
#              'dress',
#              'cover',
#              'make',
#              'draw',
#              'pour',
#              'coat',
#              'flip',
#              'toss',
#              'sit',
#              'let',
#              'dry',
#              'rub',
#              'Set',
#              'add',
#              'cut'],
#  'Nutrition': {'calories': '61', 'carbs': '13g', 'fat': '1g', 'protein': '1g'},
#  'Steps': [{'context': {'advice': [],
#                         'available_mixtures': [],
#                         'observations': ['This procedure allows the cucumbers '
#                                          'to fan'],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': ['Be sure that with each cut, the knife is '
#                                      'hitting the chopsticks, so you don’t cut '
#                                      'all the way through']},
#             'description': 'spiral the cukes, place one between 2 chopsticks, '
#                            'and cut down into thin straight slices on the top',
#             'ingredients': [],
#             'methods': ['spiral', 'place', 'cut'],
#             'step_number': 1,
#             'temperature': '2°C',
#             'time': {},
#             'tools': ['thin straight slices', 'the cukes', 'the top']},
#            {'context': {'advice': [],
#                         'available_mixtures': [],
#                         'observations': [],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': []},
#             'description': 'Flip the cucumber and make cuts at a 45 degree '
#                            'angle (diagonally) on the other side',
#             'ingredients': [],
#             'methods': ['flip', 'make'],
#             'step_number': 2,
#             'temperature': {},
#             'time': {},
#             'tools': ['the other side', 'the cucumber', 'cuts']},
#            {'context': {'advice': [],
#                         'available_mixtures': [],
#                         'observations': [],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': []},
#             'description': 'Repeat with remaining cukes',
#             'ingredients': [],
#             'methods': ['repeat', 'remain'],
#             'step_number': 3,
#             'temperature': {},
#             'time': {},
#             'tools': ['remaining cukes']},
#            {'context': {'advice': [],
#                         'available_mixtures': [],
#                         'observations': [],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': []},
#             'description': 'Place spiraled cucumbers in a large bowl',
#             'ingredients': ['cucumbers'],
#             'methods': ['place', 'spiral'],
#             'step_number': 4,
#             'temperature': {},
#             'time': {},
#             'tools': ['a large bowl']},
#            {'context': {'advice': [],
#                         'available_mixtures': [],
#                         'observations': [],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': []},
#             'description': 'Sprinkle with salt, and gently rub salt in',
#             'ingredients': ['salt'],
#             'methods': ['sprinkle', 'rub'],
#             'step_number': 5,
#             'temperature': {},
#             'time': {},
#             'tools': []},
#            {'context': {'advice': [],
#                         'available_mixtures': [],
#                         'observations': [],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': ['avoid over softening']},
#             'description': 'Set aside to draw out moisture, but no longer than '
#                            '10 minutes to avoid over softening',
#             'ingredients': [],
#             'methods': ['Set', 'draw', 'avoid', 'soften'],
#             'step_number': 6,
#             'temperature': {},
#             'time': '10 minute',
#             'tools': ['moisture']},
#            {'context': {'advice': [],
#                         'available_mixtures': [],
#                         'observations': [],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': []},
#             'description': 'Rinse well with cold water to remove salt, and pat '
#                            'dry with a paper towel',
#             'ingredients': ['salt'],
#             'methods': ['rinse', 'remove', 'dry'],
#             'step_number': 7,
#             'temperature': {},
#             'time': {},
#             'tools': ['a paper towel', 'cold water', 'pat']},
#            {'context': {'advice': [],
#                         'available_mixtures': [],
#                         'observations': [],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': []},
#             'description': 'Return to the bowl, and add onions',
#             'ingredients': ['onions'],
#             'methods': ['return', 'add'],
#             'step_number': 8,
#             'temperature': {},
#             'time': {},
#             'tools': ['the bowl']},
#            {'context': {'advice': [],
#                         'available_mixtures': [],
#                         'observations': ['until well combined'],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': []},
#             'description': 'For dressing, whisk vinegar, honey, soy sauce, '
#                            'sesame oil, fish sauce, garlic, and red pepper '
#                            'flakes in a small bowl until well combined',
#             'ingredients': ['whisk vinegar',
#                             'pepper flakes',
#                             'sesame oil',
#                             'fish sauce',
#                             'red pepper',
#                             'soy sauce',
#                             'garlic',
#                             'honey'],
#             'methods': ['for', 'whisk', 'combine'],
#             'step_number': 9,
#             'temperature': {},
#             'time': {},
#             'tools': ['a small bowl']},
#            {'context': {'advice': [],
#                         'available_mixtures': ['mixture_step_9'],
#                         'observations': ['until well coated'],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': []},
#             'description': 'Pour dressing over cucumber-onion mixture, and '
#                            'gently toss until well coated',
#             'ingredients': [],
#             'methods': ['pour', 'dress', 'toss', 'coat'],
#             'step_number': 10,
#             'temperature': {},
#             'time': {},
#             'tools': ['cucumber-onion mixture']},
#            {'context': {'advice': [],
#                         'available_mixtures': ['mixture_step_9'],
#                         'observations': ['until ready to serve'],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': []},
#             'description': 'Let cucumbers sit at room temperature for about 5 '
#                            'to 10 minutes, or cover and move to the fridge '
#                            'until ready to serve',
#             'ingredients': ['cucumbers'],
#             'methods': ['let', 'sit', 'cover', 'move', 'serve'],
#             'step_number': 11,
#             'temperature': {},
#             'time': {'max': '10 minute', 'min': '5 minute'},
#             'tools': ['room temperature', 'the fridge']},
#            {'context': {'advice': [],
#                         'available_mixtures': ['mixture_step_9'],
#                         'observations': [],
#                         'oven_preheated': False,
#                         'oven_temperature': None,
#                         'references': [],
#                         'warnings': []},
#             'description': 'Gently toss again before serving',
#             'ingredients': [],
#             'methods': ['gently', 'toss', 'serve'],
#             'step_number': 12,
#             'temperature': {},
#             'time': {},
#             'tools': []}],
#  'Tools': ['cucumber-onion mixture',
#            'thin straight slices',
#            'room temperature',
#            'remaining cukes',
#            'the other side',
#            'a paper towel',
#            'the cucumber',
#            'a small bowl',
#            'a large bowl',
#            'cold water',
#            'the fridge',
#            'the cukes',
#            'moisture',
#            'the bowl',
#            'the top',
#            'cuts',
#            'pat'],
#  'cook_time': '15 mins',
#  'dish_intro': 'This spiral-cut spicy cucumber salad features crisp, '
#                'refreshing mini cucumbers with just the right balance of '
#                'ingredients. The spiral cut not only makes the salad look a '
#                'little fancy, but allows the cucumbers to absorb the dressing '
#                'better for fuller flavor.',
#  'dish_name': 'Spiral Spicy Cucumber Salad',
#  'prep_time': '15 mins',
#  'serving': 6,
#  'total_time': '30 mins',
#  'url': 'https://www.allrecipes.com/spiral-spicy-cucumber-salad-recipe-11814637/'}
